import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const aiDir = path.join(root, ".ai");
const contextPath = path.join(aiDir, "context.md");
const templatePath = path.join(aiDir, "templates", "task.md");

const IGNORED_DIRECTORIES = new Set([
  ".git",
  ".ai",
  ".cache",
  ".firebase",
  ".gradle",
  ".idea",
  ".next",
  ".turbo",
  ".vscode",
  "DerivedData",
  "build",
  "dist",
  "node_modules",
  "Pods",
  "lib",
]);

const IGNORED_FILES = new Set([
  ".DS_Store",
  "firebase-debug.log",
  "package-lock.json",
  "bun.lock",
  "pnpm-lock.yaml",
  "yarn.lock",
]);

function shouldIgnoreDirectory(name, relativeDir) {
  if (!IGNORED_DIRECTORIES.has(name)) return false;
  if (name === "lib") return relativeDir === "functions";
  return true;
}

function walk(currentDir, relativeDir = "") {
  const entries = fs
    .readdirSync(currentDir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name));
  const lines = [];

  for (const entry of entries) {
    const relativePath = path.join(relativeDir, entry.name).replaceAll(path.sep, "/");
    if (entry.isDirectory()) {
      if (!shouldIgnoreDirectory(entry.name, relativeDir)) {
        lines.push(`${relativePath}/`);
        lines.push(...walk(path.join(currentDir, entry.name), relativePath));
      }
      continue;
    }
    const isEnvironmentFile =
      entry.name === ".env" || entry.name.startsWith(".env.");
    if (
      !IGNORED_FILES.has(entry.name) &&
      !entry.name.endsWith(".local") &&
      !isEnvironmentFile
    ) {
      lines.push(relativePath);
    }
  }

  return lines;
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch {
    return {};
  }
}

function hasDependency(packageJson, name) {
  return Boolean(
    packageJson.dependencies?.[name] || packageJson.devDependencies?.[name],
  );
}

function stackSummary(packageJson) {
  const stack = [];
  const knownPackages = [
    ["Vite", "vite"],
    ["React", "react"],
    ["React Router", "react-router"],
    ["Tailwind CSS", "tailwindcss"],
    ["Firebase", "firebase"],
    ["Framer Motion", "framer-motion"],
    ["Lucide", "lucide-react"],
    ["Zod", "zod"],
  ];

  for (const [label, packageName] of knownPackages) {
    if (hasDependency(packageJson, packageName)) stack.push(label);
  }

  return stack.length > 0 ? stack.join(" + ") : "See package.json";
}

function renderContext() {
  const packageJson = readJson(path.join(root, "package.json"));
  const tree = walk(root);
  const generatedAt = new Date().toISOString().slice(0, 10);

  return `<!-- Generated by scripts/ai-context.mjs. Do not edit this file by hand. -->
# AI Repository Context

Generated on ${generatedAt} for **${packageJson.name || "this repository"}**.

## Stack

${stackSummary(packageJson)}

- Frontend commands use **bun**.
- Firebase Functions under \`functions/\` use **npm**.
- The source of truth for architecture and project rules is \`AGENTS.md\`.
- User-facing conventions and setup live in \`README.md\`.

## Architecture Shortcuts

| Area | Start here |
| --- | --- |
| Routes and page composition | \`src/main.tsx\`, \`src/pages/\` |
| Shared UI | \`src/components/\`, \`src/components/ui/\` |
| Firebase Auth | \`src/hooks/use-auth.ts\`, \`src/pages/Auth.tsx\` |
| Firestore client access | \`src/lib/firebase.ts\`, \`src/components/saved/\` |
| Callable function wrappers | \`src/lib/strain-api.ts\` |
| Cloud Functions | \`functions/src/index.ts\`, \`functions/src/\` |
| iOS companion | \`ios/StrainWise/\` |
| Android companion | \`android/app/src/main/\` |

## Operating Rules

- Preserve the Firebase-only architecture and existing platform parity.
- Use the existing hooks, shadcn primitives, Firebase wrappers, and route guards.
- Do not edit \`functions/lib/\`; it is compiled output.
- Do not add secrets to source, MCP config, generated context, or task files.
- Keep UI changes mobile responsive, border-based, and free of nested cards or shadows.
- Before finishing a non-trivial change, run the relevant typecheck and tests.

## Repository Tree

\`\`\`text
${tree.join("\n")}
\`\`\`
`;
}

function slugify(value) {
  const slug = value
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 72);
  return slug || "ai-task";
}

function writeContext() {
  fs.mkdirSync(aiDir, { recursive: true });
  const context = renderContext();
  fs.writeFileSync(contextPath, context);
  return context;
}

function writeTask(description, force) {
  const context = writeContext();
  const template = fs.readFileSync(templatePath, "utf8");
  const taskPath = path.join(aiDir, "tasks", `${slugify(description)}.md`);

  if (fs.existsSync(taskPath) && !force) {
    throw new Error(
      `${path.relative(root, taskPath)} already exists; pass --force to replace it`,
    );
  }

  const task = template
    .replaceAll("{{DESCRIPTION}}", description.trim())
    .replaceAll("{{REPOSITORY_CONTEXT}}", context);
  fs.mkdirSync(path.dirname(taskPath), { recursive: true });
  fs.writeFileSync(taskPath, task);
  return taskPath;
}

function checkWorkspace() {
  const requiredFiles = [
    "AGENTS.md",
    "README.md",
    "package.json",
    ".ai/templates/task.md",
    ".ai/skills/strainease-change/SKILL.md",
    ".githooks/pre-commit",
    ".githooks/pre-push",
    ".mcp.json",
  ];
  const missing = requiredFiles.filter(
    (file) => !fs.existsSync(path.join(root, file)),
  );
  if (missing.length > 0) {
    throw new Error(`AI workspace is missing: ${missing.join(", ")}`);
  }

  const mcp = readJson(path.join(root, ".mcp.json"));
  if (!mcp.mcpServers || typeof mcp.mcpServers !== "object") {
    throw new Error(".mcp.json must contain an mcpServers object");
  }
  if (walk(root).length === 0) throw new Error("Repository tree is empty");
}

const args = process.argv.slice(2);
const quiet = args.includes("--quiet");
const force = args.includes("--force");
const check = args.includes("--check");
const taskIndex = args.indexOf("--task");

try {
  if (check) {
    checkWorkspace();
    if (!quiet) console.log("AI workspace configuration is valid.");
  } else if (taskIndex !== -1) {
    const description = args
      .slice(taskIndex + 1)
      .filter(
        (arg) => arg !== "--" && arg !== "--force" && arg !== "--quiet",
      )
      .join(" ")
      .trim();
    if (!description) {
      throw new Error("Usage: bun run ai:task -- \"Describe the change\"");
    }
    const taskPath = writeTask(description, force);
    if (!quiet) console.log(`Generated ${path.relative(root, taskPath)}`);
  } else {
    writeContext();
    if (!quiet) console.log(`Generated ${path.relative(root, contextPath)}`);
  }
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
